#!/bin/bash

chroot_dir=/srv/chroot/slack32

if [ -n "${Xexport}" ] && $Xexport ;then
	xhost +localhost
fi

if [ -n "${CHROOT_USER}" ] ;then
	sudo chroot --userspec=`id -u ${CHROOT_USER}` $chroot_dir $*
else
	sudo chroot $chroot_dir $*
fi

echo done
